- name: Configure the Gateway Router
  hosts: ot-gateway
  become: yes
  roles:
    - router

- name: Configure the Engineering Workstation
  hosts: engineering-station
  become: yes
  roles:
    - ews

- name: Configure the Software PLC Node
  hosts: openplc-node
  become: yes
  roles:
    - openplc
